In [1]:
import numpy as np

In [4]:
myarray = np.array([1,2,4,5,6,7,8,9,10],np.int8)  # int8 means the array elements are given the 8 bits space

In [5]:
myarray

array([ 1,  2,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [7]:
myarray[-1]

10

In [8]:
myarray.shape

(9,)

In [9]:
myarray.dtype

dtype('int8')

In [11]:
myarray1 = np.array([[1,2,3,4,5]]) # now it is 2D array

In [12]:
myarray1

array([[1, 2, 3, 4, 5]])

In [15]:
myarray1[0,0] = 50

In [16]:
myarray1

array([[50, 50,  3,  4,  5]])

# Array Creation : conversion from other python structures

In [18]:
listarray = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [19]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
listarray.dtype

dtype('int32')

In [21]:
listarray.shape

(3, 3)

In [22]:
listarray.size

9

In [23]:
zeros = np.zeros((5,5))

In [24]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [25]:
num = np.arange(1,16)

In [26]:
num

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [27]:
lspace = np.linspace(1,11,10)

In [28]:
lspace

array([ 1.        ,  2.11111111,  3.22222222,  4.33333333,  5.44444444,
        6.55555556,  7.66666667,  8.77777778,  9.88888889, 11.        ])

In [30]:
lspace = np.linspace(1,50,10)

In [31]:
lspace

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [32]:
lspace = np.linspace(10,100,10)

In [33]:
lspace

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [34]:
emp = np.empty((5,5))

In [35]:
emp

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [37]:
ide = np.identity((5))

In [38]:
ide

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [39]:
ide.shape

(5, 5)

In [40]:
arr = np.arange(99)

In [41]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [42]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [43]:
arr.reshape(33,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [30, 31, 32],
       [33, 34, 35],
       [36, 37, 38],
       [39, 40, 41],
       [42, 43, 44],
       [45, 46, 47],
       [48, 49, 50],
       [51, 52, 53],
       [54, 55, 56],
       [57, 58, 59],
       [60, 61, 62],
       [63, 64, 65],
       [66, 67, 68],
       [69, 70, 71],
       [72, 73, 74],
       [75, 76, 77],
       [78, 79, 80],
       [81, 82, 83],
       [84, 85, 86],
       [87, 88, 89],
       [90, 91, 92],
       [93, 94, 95],
       [96, 97, 98]])

In [51]:
arr1 = np.arange(1,101)

In [52]:
arr1

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [53]:
arr1.reshape(10,10)

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [57]:
new_arr=arr.ravel()

In [58]:
new_arr.shape

(100,)

# Axis operations

In [59]:
# in one dimensional array there exist only one axis i.e axis 0
# axis 0 goes downward
# axis 1 goes left to right

In [60]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [61]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [62]:
arr.sum(axis=0)

array([12, 15, 18])

In [63]:
arr.sum(axis=1)

array([ 6, 15, 24])

In [64]:
arr.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [65]:
for item in arr.flat:
    print(item)

1
2
3
4
5
6
7
8
9


In [66]:
arr.ndim

2

In [67]:
arr.size

9

In [68]:
arr.itemsize

4

In [69]:
arr.nbytes

36

In [70]:
one = np.array([1,2,3,5,67,67,56])

In [71]:
one

array([ 1,  2,  3,  5, 67, 67, 56])

In [72]:
one.argmax()

4

In [73]:
one.argmin()

0

In [75]:
one.argsort()

array([0, 1, 2, 3, 6, 4, 5], dtype=int64)

In [76]:
one.argmax(axis=0)

4

In [77]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [78]:
arr.argmax(axis=0)

array([2, 2, 2], dtype=int64)

In [79]:
arr.argmax(axis=1)

array([2, 2, 2], dtype=int64)

In [80]:
ar = np.array([[43,55,7],[4,67,6],[54,78,43]])

In [81]:
ar

array([[43, 55,  7],
       [ 4, 67,  6],
       [54, 78, 43]])

In [82]:
ar.argmax(axis=1)

array([1, 1, 1], dtype=int64)

In [83]:
ar.argmax(axis=0)

array([2, 2, 2], dtype=int64)

In [85]:
arr.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [86]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [87]:
ar

array([[43, 55,  7],
       [ 4, 67,  6],
       [54, 78, 43]])

In [88]:
new = np.vstack((arr,ar))

In [89]:
new

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [43, 55,  7],
       [ 4, 67,  6],
       [54, 78, 43]])

In [90]:
new1 = np.hstack((arr,ar))

In [91]:
new1

array([[ 1,  2,  3, 43, 55,  7],
       [ 4,  5,  6,  4, 67,  6],
       [ 7,  8,  9, 54, 78, 43]])

In [92]:
arr + ar

array([[44, 57, 10],
       [ 8, 72, 12],
       [61, 86, 52]])

In [93]:
ar - arr

array([[42, 53,  4],
       [ 0, 62,  0],
       [47, 70, 34]])

In [94]:
ar * arr

array([[ 43, 110,  21],
       [ 16, 335,  36],
       [378, 624, 387]])

In [95]:
ar *0

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [96]:
ar*5

array([[215, 275,  35],
       [ 20, 335,  30],
       [270, 390, 215]])

In [97]:
arr*-2

array([[ -2,  -4,  -6],
       [ -8, -10, -12],
       [-14, -16, -18]])

In [98]:
np.sqrt(arr)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [99]:
np.sqrt(ar)

array([[6.55743852, 7.41619849, 2.64575131],
       [2.        , 8.18535277, 2.44948974],
       [7.34846923, 8.83176087, 6.55743852]])

In [100]:
ar.sum()

357

In [101]:
arr.sum()

45

In [102]:
ar.max()

78

In [103]:
arr.max()

9

In [104]:
ar.min()

4

In [105]:
arr.min()

1

In [106]:
np.where(ar>50)

(array([0, 1, 2, 2], dtype=int64), array([1, 1, 0, 1], dtype=int64))

In [109]:
np.where(arr>8)

(array([2], dtype=int64), array([2], dtype=int64))

In [110]:
np.count_nonzero(arr)

9

In [112]:
np.nonzero(arr)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [113]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [114]:
arr[2][2]=0

In [115]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 0]])

In [116]:
arr.nonzero()

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))

In [117]:
import sys

In [119]:
py_ar = [3,54,65,8]

In [120]:
ch_ar = np.array(py_ar)

In [122]:
sys.getsizeof(1)*len(py_ar)

112

In [123]:
ch_ar.itemsize * ch_ar.size

16